name: circular_check_box
description: Same as the regular checkbox, but circular!
version: 1.0.3
author: Mash Ibtesum <mashnoon33@gmail.com>
homepage: http://mash.studio/
repository: https://github.com/mashnoon33/circular_check_box.git

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
